version: '3'

services:
  check:
    image: gonzalo123.check
    restart: always
    volumes:
    - ./src/check:/code/src
    depends_on:
    - influxdb
    build:
      context: ./src
      dockerfile: .docker/Dockerfile-check
    networks:
    - app-network
    command: /bin/sh start.sh
  influxdb:
    image: influxdb:latest
    restart: always
    environment:
    - INFLUXDB_DB=${INFLUXDB_DB}
    - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
    - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
    volumes:
    - influxdb-data:/data
    networks:
    - app-network
    ports:
    - "8086:8086"
  grafana:
    build:
      context: ./src
      dockerfile: .docker/Dockerfile-grafana
    restart: always
    environment:
    - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
    - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME}
    - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
    - GF_USERS_ALLOW_ORG_CREATE=${GF_USERS_ALLOW_ORG_CREATE}
    - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
    ports:
    - "3000:3000"
    depends_on:
    - influxdb
    networks:
    - app-network
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
    - ./src/mosquitto/conf:/mosquitto/conf/
    networks:
    - app-network
    ports:
    - "1883:1883"
    - "9001:9001"
  mqtt-to-influx:
    image: pulli-mqtt
    restart: always
    volumes:
      - ./src/mqtt_to_influx:/code/src
    depends_on:
      - influxdb
    build:
      context: ./src
      dockerfile: .docker/Dockerfile-mqtt-to-influx
    command: ["python", "app.py"]
    networks:
      - app-network

volumes:
  influxdb-data:
    driver: local

networks:
  app-network:
    driver: bridge

